language: go
sudo: false
before_install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      sudo apt-get -qq update
      sudo apt-get install pocl
    fi;
  - make get-tools
install: true
script:
  - make ci
go:
  - 1.7
  - 1.8
  - master
notifications:
  email:
    - talek-dev@googlegroups.com
